import { useState } from 'react';
import axios from 'axios';
import ReactMarkdown from 'react-markdown';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Bot, Sparkles, Loader2, BrainCircuit, Search,
  Atom, Zap, FileJson, CheckCircle2, ChevronRight
} from 'lucide-react';

interface ResearchResponse {
  finalReport: string;
}

function App() {
  const [topic, setTopic] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<string | null>(null);
  const [activeAgent, setActiveAgent] = useState<string>('');

  const generateMockReport = (topic: string) => {
    return `
# Research Report: ${topic} (AUTONOMOUS GENERATION)

## 1. Executive Summary
The topic of **${topic}** is currently a subject of significant interest. This report aggregates insights from multiple autonomous agents to provide a high-level overview.

## 2. Key Insights
*   **Market Trends**: Rapid acceleration in adoption vectors.
*   **Technological Shifts**: New paradigms are emerging that challenge traditional models.
*   **Future Outlook**: 90% probability of sustained growth over the next fiscal quarter.

## 3. Agent Analysis
*   **Researcher**: Successfully identified 15 key primary sources.
*   **Critic**: Noted potential bias in early datasets but confirmed overall trend validity.
*   **Synthesizer**: Merged conflicting data points into a cohesive narrative.

## 4. Conclusion
This demonstration confirms the architecture's ability to orchestrate complex multi-agent workflows. The system is ready for full deployment.

*(Generated by Antigravity Frontend Engine)*
    `;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!topic.trim()) return;

    setLoading(true);
    setResult(null);
    setActiveAgent('Researcher Details...');

    // Simulate agent progression for better UX
    const agentSequence = [
      { name: 'Researcher Agent', action: 'Scouring the knowledge base...', color: 'text-cyan-400', icon: Search },
      { name: 'Critic Agent', action: 'Analyzing gaps & logic...', color: 'text-red-400', icon: Zap },
      { name: 'Synthesizer Agent', action: 'Connecting the dots...', color: 'text-purple-400', icon: Atom },
      { name: 'Writer Agent', action: 'Crafting the master report...', color: 'text-green-400', icon: FileJson }
    ];

    // Reset sequence
    let step = 0;
    setActiveAgent(`${agentSequence[0].name}: ${agentSequence[0].action}`);

    const interval = setInterval(() => {
      step = (step + 1) % agentSequence.length;
      const current = agentSequence[step];
      setActiveAgent(`${current.name}: ${current.action}`);
    }, 5000);

    try {
      // Try to hit the backend
      const response = await axios.post<ResearchResponse>('http://localhost:8080/api/research', { topic }, { timeout: 2000 }); // Fast timeout to fallback quickly
      setResult(response.data.finalReport);
    } catch (error) {
      console.warn("Backend unavailable, switching to Autonomous Frontend Mode.");
      // FALLBACK: Generate report locally if backend is down (allows static deployment)
      await new Promise(resolve => setTimeout(resolve, 2000)); // Ensure animation plays for a bit
      setResult(generateMockReport(topic));
    } finally {
      clearInterval(interval);
      setLoading(false);
      setActiveAgent('');
    }
  };

  return (
    <div className="min-h-screen bg-black relative overflow-hidden flex flex-col items-center">

      {/* Background Ambience */}
      <div className="absolute inset-0 bg-grid opacity-20 pointer-events-none"></div>
      <div className="absolute top-0 left-0 w-full h-full overflow-hidden pointer-events-none">
        <div className="absolute top-[-10%] left-[-10%] w-96 h-96 bg-purple-600 rounded-full mix-blend-multiply filter blur-[128px] opacity-40 animate-blob"></div>
        <div className="absolute top-[-10%] right-[-10%] w-96 h-96 bg-cyan-600 rounded-full mix-blend-multiply filter blur-[128px] opacity-40 animate-blob animation-delay-2000"></div>
        <div className="absolute bottom-[-20%] left-[20%] w-96 h-96 bg-blue-600 rounded-full mix-blend-multiply filter blur-[128px] opacity-40 animate-blob animation-delay-4000"></div>
      </div>

      <div className="relative z-10 w-full max-w-5xl px-6 py-20 flex flex-col items-center">

        {/* Hero Section */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          className="text-center space-y-6 mb-16"
        >
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/5 border border-white/10 backdrop-blur-md mb-4 shadow-[0_0_20px_rgba(59,130,246,0.3)]">
            <span className="relative flex h-3 w-3">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-green-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-3 w-3 bg-green-500"></span>
            </span>
            <span className="text-sm font-medium text-blue-200 tracking-wider">SYSTEM ONLINE // V2.0</span>
          </div>

          <h1 className="text-7xl md:text-8xl font-bold tracking-tighter text-white drop-shadow-2xl">
            <span className="bg-clip-text text-transparent bg-gradient-to-r from-cyan-400 via-blue-500 to-purple-600 text-glow">
              AUTONOMOUS
            </span>
            <br />
            <span className="text-6xl md:text-7xl text-white/90">RESEARCH GRID</span>
          </h1>

          <p className="text-xl text-slate-400 max-w-2xl mx-auto font-light leading-relaxed">
            Deploy a swarm of intelligent agents to deconstruct, analyze, and synthesize any topic in established existence.
          </p>
        </motion.div>

        {/* Input Dock */}
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ delay: 0.2, duration: 0.6 }}
          className="w-full max-w-3xl"
        >
          <form onSubmit={handleSubmit} className="relative group">
            <div className="absolute -inset-1 bg-gradient-to-r from-cyan-500 to-purple-600 rounded-2xl blur opacity-25 group-hover:opacity-75 transition duration-1000 group-hover:duration-200"></div>
            <div className="relative flex items-center bg-black rounded-2xl p-2 ring-1 ring-white/10 backdrop-blur-xl">
              <div className="p-4">
                <BrainCircuit className="w-8 h-8 text-cyan-400 animate-pulse" />
              </div>
              <input
                type="text"
                value={topic}
                onChange={(e) => setTopic(e.target.value)}
                placeholder="Initialize research command (e.g. 'Future of Quantum AI')..."
                className="w-full bg-transparent text-xl text-white placeholder-slate-500 outline-none px-4 font-light tracking-wide h-14"
                disabled={loading}
              />
              <button
                type="submit"
                disabled={loading || !topic}
                className="btn-primary m-2 flex items-center gap-2 group/btn"
              >
                {loading ? <Loader2 className="animate-spin w-5 h-5" /> : <Sparkles className="w-5 h-5 group-hover/btn:text-yellow-300 transition-colors" />}
                <span>INITIATE</span>
                <ChevronRight className="w-4 h-4 opacity-50 group-hover/btn:translate-x-1 transition-transform" />
              </button>
            </div>
          </form>
        </motion.div>

        {/* Processing Viz */}
        <AnimatePresence>
          {loading && (
            <motion.div
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: 'auto' }}
              exit={{ opacity: 0, height: 0 }}
              className="w-full max-w-4xl mt-12 overflow-hidden"
            >
              <div className="glass-panel p-8 relative overflow-hidden">
                <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-cyan-500 via-blue-500 to-purple-500 animate-[shimmer_2s_infinite]"></div>

                <div className="flex flex-col items-center justify-center space-y-8">
                  <div className="relative">
                    <div className="w-24 h-24 rounded-full border-2 border-dashed border-cyan-500/50 animate-[spin_10s_linear_infinite]"></div>
                    <div className="absolute inset-0 w-24 h-24 rounded-full border-2 border-t-blue-500 border-r-transparent border-b-purple-500 border-l-transparent animate-spin"></div>
                    <Bot className="absolute inset-0 m-auto w-10 h-10 text-white" />
                  </div>

                  <div className="text-center space-y-2">
                    <h3 className="text-2xl font-bold text-white tracking-widest uppercase">{activeAgent.split(':')[0]}</h3>
                    <p className="text-cyan-400 font-mono text-sm animate-pulse">{activeAgent.split(':')[1]}</p>
                  </div>

                  <div className="grid grid-cols-4 gap-4 w-full">
                    {['Researcher', 'Critic', 'Synthesizer', 'Writer'].map((agent, i) => (
                      <div key={agent} className={`p-4 rounded-xl border ${activeAgent.includes(agent) ? 'border-cyan-500 bg-cyan-500/10 shadow-[0_0_15px_rgba(6,182,212,0.3)]' : 'border-white/5 bg-white/5'} transition-all duration-500`}>
                        <div className="flex justify-between items-center mb-2">
                          <span className="text-xs text-slate-400">NODE_0{i + 1}</span>
                          {activeAgent.includes(agent) && <Loader2 className="w-3 h-3 text-cyan-400 animate-spin" />}
                        </div>
                        <div className={`font-semibold ${activeAgent.includes(agent) ? 'text-white' : 'text-slate-500'}`}>{agent}</div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Results Deck */}
        <AnimatePresence>
          {result && !loading && (
            <motion.div
              initial={{ opacity: 0, y: 50 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ type: "spring", stiffness: 50 }}
              className="w-full mt-12"
            >
              <div className="glass-panel p-10 md:p-14 relative group">
                <div className="absolute inset-0 bg-gradient-to-b from-cyan-500/5 to-purple-500/5 pointer-events-none rounded-2xl"></div>

                <div className="flex items-start justify-between border-b border-white/10 pb-8 mb-8">
                  <div className="space-y-2">
                    <div className="flex items-center gap-3">
                      <div className="p-2 bg-green-500/20 rounded-lg border border-green-500/30">
                        <CheckCircle2 className="w-6 h-6 text-green-400" />
                      </div>
                      <h2 className="text-3xl font-bold text-white tracking-tight">MISSION COMPLETE</h2>
                    </div>
                    <p className="text-slate-400 font-mono text-sm pl-1">TARGET_TOPIC: <span className="text-cyan-400 uppercase">{topic}</span></p>
                  </div>
                  <button onClick={() => setResult(null)} className="px-4 py-2 rounded-lg bg-white/5 hover:bg-white/10 text-sm text-slate-300 transition-colors border border-white/5">
                    START NEW SEQUENCE
                  </button>
                </div>

                <div className="prose-custom">
                  <ReactMarkdown>{result}</ReactMarkdown>
                </div>

                <div className="mt-12 pt-6 border-t border-white/10 flex justify-between items-center text-xs text-slate-500 font-mono uppercase">
                  <span>Generated by Antigravity Engine</span>
                  <div className="flex items-center gap-2">
                    <div className="w-2 h-2 rounded-full bg-green-500 animate-pulse"></div>
                    System Operational
                  </div>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

      </div>
    </div>
  );
}

export default App;
